// fix-socks.js — creates a stub if socks/build/index.js is missing (Render build quirk)
const fs = require('fs');
const path = require('path');

try {
  const modDir = path.join(__dirname, '..', 'node_modules', 'socks');
  if (!fs.existsSync(modDir)) {
    console.log('[fix-socks] socks not installed, skipping');
    process.exit(0);
  }

  const buildDir = path.join(modDir, 'build');
  const indexJs = path.join(buildDir, 'index.js');

  fs.mkdirSync(buildDir, { recursive: true });

  if (!fs.existsSync(indexJs)) {
    fs.writeFileSync(
      indexJs,
      '// stub generated by fix-socks.js to avoid runtime require errors\nmodule.exports = {};\n',
      'utf8'
    );
    console.log('[fix-socks] created stub:', path.relative(process.cwd(), indexJs));
  } else {
    console.log('[fix-socks] already present:', path.relative(process.cwd(), indexJs));
  }
} catch (e) {
  console.log('[fix-socks] skipped:', e.message);
}